name: Keep Streamlit Awake

on:
  schedule:
    # roda a cada 10 horas 
    - cron: "0 */10 * * *"
  workflow_dispatch: {}   

permissions:
  contents: write    

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Empty commit
        run: |
          git commit --allow-empty -m "chore: keep alive"

      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
